echo 'In the /etc/sudoers file we see different configurations'
echo 'This is what the /etc/sudoers configuration means'
echo ''
echo 'User assignment'
echo 'user1     ALL=(ALL:ALL) ALL'
echo ''
echo 'Group assignment'
echo '%group1   ALL=(ALL:ALL) ALL'
echo ''
echo 'Explaining configuration'
echo 'ALL            =    ( ALL            : ALL              )  ALL'
echo 'Which hosts           Run as user      Run as group        Which commands are allowed to be run as sudo  '
echo ''
echo 'ALL            =    ( ALL            : ALL              )  NOPASSWD: ALL'
echo 'Which hosts           Run as user      Run as group        Which commands are allowed to be run as sudo without a password '
